# Generated by Django 4.2.8 on 2025-01-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Product_Code')),
                ('style_no', models.CharField(max_length=50, verbose_name='Style_No')),
                ('product_type', models.CharField(max_length=100, verbose_name='Product_Type')),
                ('designer_head', models.CharField(max_length=100, verbose_name='Designer_Head')),
                ('entered_by', models.CharField(max_length=100, verbose_name='Entered_By')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('season', models.CharField(max_length=50, verbose_name='Season')),
                ('fabric', models.CharField(max_length=100, verbose_name='Fabric')),
                ('value_driver', models.CharField(max_length=100, verbose_name='Value_Driver')),
                ('sustainable', models.BooleanField(verbose_name='Sustainable')),
                ('designer_status', models.CharField(max_length=50, verbose_name='Designer_Status')),
                ('dmm_status', models.CharField(max_length=50, verbose_name='DMM_Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Product_Details',
            },
        ),
    ]
