# Generated by Django 4.2.8 on 2025-01-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Showroom_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
