# Generated by Django 4.2.8 on 2025-01-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Showroom_db', '0002_productdetails_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='back_image/'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='details_image',
            field=models.ImageField(blank=True, null=True, upload_to='details_image/'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='fabric_image',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_image/'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='front_image/'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='inspiration_image',
            field=models.ImageField(blank=True, null=True, upload_to='inspiration_image/'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_image/'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='sleeve_image',
            field=models.ImageField(blank=True, null=True, upload_to='sleeve_image/'),
        ),
    ]
