# Generated by Django 4.2.8 on 2025-01-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Showroom_db', '0004_usercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
