# Generated by Django 4.2.8 on 2025-01-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Showroom_db', '0005_alter_usercart_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
