# Generated by Django 4.2.8 on 2025-01-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Showroom_db', '0007_usercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='style_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Style_No'),
        ),
    ]
