# Generated by Django 4.2.8 on 2025-01-17 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Showroom_db', '0008_alter_productdetails_style_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='designer_head',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designer_Head'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='designer_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Designer_Status'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='dmm_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DMM_Status'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='entered_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entered_By'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='fabric',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabric'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product_Code'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product_Type'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='sustainable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sustainable'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='value_driver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Value_Driver'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='is_active',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart_products', to='Virtual_Showroom_db.productdetails'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
