# Generated by Django 5.1.6 on 2025-08-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Showroom_db', '0009_alter_productdetails_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productdetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usercart',
            table=None,
        ),
    ]
